version: "3.9"
services:
    auth_backend:
      image: prauxy/authentication
      ports:
        - "8080:8080"
      links:
        - auth_mongo
        - redis
    redis:
      image: redis
    auth_mongo:
      image: mongo