name: Authentication Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build Authentication Docker container
      run: ./gh-actions-build.sh

    - name: Unit test Authentication using Docker container
      run: docker-compose -f authentication-tests/docker-compose.test.yaml up --exit-code-from testing

    - name: Stand up backend and front end Authentication containers for e2e tests
      run: docker-compose -f authentication/docker-compose.yaml -f authentication/tests-compose.yaml -d
    
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        spec: authentication/tests/cypress/integration  
